/**
 * withWorkflow — the headline SDK primitive.
 *
 *   await withWorkflow(
 *     { name: "order.fulfillment", businessKeys: { order_id: "1234" } },
 *     async () => {
 *       await medusaCreateOrder();
 *       await pushToBack40();
 *     },
 *   );
 *
 * Wraps `fn` in a root span with the canonical `betterlog.workflow.*`
 * attributes. The span context is propagated automatically — any recordStep
 * call inside `fn` becomes a child of this workflow.
 *
 * The workflow_id is server-generated by default (ulid). Callers can pass
 * one for cross-process workflows where the ID needs to be deterministic.
 */

import { SpanStatusCode } from "@opentelemetry/api";
import { ulid } from "ulid";
import { OTEL_ATTR } from "@betterlog/shared";
import { withActiveWorkflow } from "./context.js";
import { getTracer } from "./otel.js";

export interface WithWorkflowOptions {
  /** Workflow name, e.g. "order.fulfillment". */
  name: string;
  /** Business-meaningful identifiers, e.g. { order_id: "1234" }. */
  businessKeys: Record<string, string>;
  /** Defaults to a fresh ulid. */
  workflowId?: string;
  /** Defaults to "0.0.0". */
  version?: string;
  /** Defaults to NODE_ENV or "development". */
  environment?: string;
  /** Free-form metadata, stored alongside the workflow. */
  metadata?: Record<string, unknown>;
}

export async function withWorkflow<T>(
  opts: WithWorkflowOptions,
  fn: (ctx: { workflowId: string }) => Promise<T>,
): Promise<T> {
  const workflowId = opts.workflowId ?? ulid();
  const environment = opts.environment ?? process.env.NODE_ENV ?? "development";
  const version = opts.version ?? "0.0.0";

  const attributes: Record<string, string> = {
    [OTEL_ATTR.workflowId]: workflowId,
    [OTEL_ATTR.workflowName]: opts.name,
    [OTEL_ATTR.workflowVersion]: version,
    [OTEL_ATTR.workflowEnvironment]: environment,
  };
  for (const [key, value] of Object.entries(opts.businessKeys)) {
    attributes[`${OTEL_ATTR.businessPrefix}${key}`] = value;
  }
  if (opts.metadata !== undefined) {
    try {
      attributes["betterlog.workflow.metadata"] = JSON.stringify(opts.metadata);
    } catch {
      // ignore unserializable metadata
    }
  }

  const tracer = getTracer();
  return withActiveWorkflow(
    { id: workflowId, name: opts.name, version, environment },
    () =>
      tracer.startActiveSpan(`workflow:${opts.name}`, { attributes }, async (span) => {
        try {
          const result = await fn({ workflowId });
          span.setStatus({ code: SpanStatusCode.OK });
          return result;
        } catch (err) {
          const message = err instanceof Error ? err.message : String(err);
          span.recordException(err instanceof Error ? err : new Error(message));
          span.setStatus({ code: SpanStatusCode.ERROR, message });
          throw err;
        } finally {
          span.end();
        }
      }),
  );
}
